[build]
publish = "."
command = ""

# Proxy API calls to Fly
[[redirects]]
  from = "/api/*"
  to = "https://bethub-api.fly.dev/api/:splat"
  status = 200
  force = true

# SPA catch-all so /promo, /news, etc. still serve index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
