# netlify.toml
[build]
  publish = "."

# Proxy API calls
[[redirects]]
  from = "/api/*"
  to   = "https://bethub-api.fly.dev/api/:splat"
  status = 200
  force  = true

# SPA fallback (so /#/… or any route resolves to index.html)
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to   = "https://bethub-api.fly.dev/api/:splat"
  status = 200
  force  = true